import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTagEntity1688909348988 implements MigrationInterface {
	name = "AddTagEntity1688909348988";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
			CREATE TABLE "tag" (
				"id"        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				"parent_id" integer,

				CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"),
				CONSTRAINT "FK_fdb4c6bd27ccc3d95a8027cd732" FOREIGN KEY ("parent_id")
					REFERENCES "tag"("id") ON DELETE SET NULL ON UPDATE NO ACTION
			)`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "tag"`);
	}
}
