import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCategoryTranslationEntity1688680257385 implements MigrationInterface {
	name = "AddCategoryTranslationEntity1688680257385";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
			CREATE TABLE "category_translation" (
				"id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				"category_id" integer NOT NULL,
				"language"    character(2) NOT NULL,
				"name"        text NOT NULL,
				"text"        text NOT NULL,

				CONSTRAINT "UQ_72008e0cd4b2335e4eeb0b21a0a" UNIQUE ("category_id", "language"),
				CONSTRAINT "PK_eeafea0891382f348c30a2a6bc2" PRIMARY KEY ("id"),
				CONSTRAINT "FK_e2c538aafd6262f061936460f1d" FOREIGN KEY ("category_id")
					REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION
			)`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "category_translation"`);
	}
}
