import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProductEditionEntity1688727902946 implements MigrationInterface {
	name = "AddProductEditionEntity1688727902946";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
			CREATE TABLE "product_edition" (
				"id"         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				"product_id" integer NOT NULL,
				"name"       text NOT NULL,
				"price"      numeric(7,2) NOT NULL,
				"available"  boolean NOT NULL DEFAULT true,

				CONSTRAINT "PK_25a21ffdeae9729dfb15d1ed2c5" PRIMARY KEY ("id"),
				CONSTRAINT "FK_8deaa2e2ec27ecdfc99f5c61adc" FOREIGN KEY ("product_id")
					REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
				CONSTRAINT "CHK_22ad096df1c788d07b9f34d210" CHECK ("price" >= 0)
			)`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "product_edition"`);
	}
}
