import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProductTranslationEntity1688909309117 implements MigrationInterface {
	name = "AddProductTranslationEntity1688909309117";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
			CREATE TABLE "product_translation" (
				"id"                  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				"product_id"          integer NOT NULL,
				"language"            character(2) NOT NULL,
				"name"                text NOT NULL,
				"description"         text NOT NULL,
				"preview_description" text NOT NULL,
				"text"                text NOT NULL,
				
				CONSTRAINT "UQ_c16e540c11dbfdbccd8825bf688" UNIQUE ("product_id", "language"),
				CONSTRAINT "PK_62d00fbc92e7a495701d6fee9d5" PRIMARY KEY ("id"),
				CONSTRAINT "FK_045befe4da0d3c207a981f4e88b" FOREIGN KEY ("product_id")
					REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
			)`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "product_translation"`);
	}
}
