service: coffee-e-shop

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  apiGateway:
    shouldStartNameWithService: true

  environment:
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodbURL}
    S3_ENDPOINT: ${self:custom.endpoints.s3URL}

    IMAGES_BUCKET_NAME: ${self:service}-images-bucket
    IMAGES_TABLE_NAME: ${self:service}-images-table

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*Object"

      Resource: arn:aws:s3:::${self:provider.environment.IMAGES_BUCKET_NAME}/*

functions:
  nestjs-backend:
    handler: src/lambda.handler
    memorySize: 128

    events:
      - http:
          method: any
          path: /{proxy+}

resources:
  Resources:
    ImagesBucket: ${file(resources/Images.bucket.yml)}
    ImagesTable: ${file(resources/Images.table.yml)}

custom:
  s3:
    host: localhost
    directory: /tmp

  endpoints:
    dynamodbURL: http://localhost:8000
    s3URL: http://localhost:4569
