Type: AWS::DynamoDB::Table
Properties:
  TableName: ${self:provider.environment.PRODUCTS_TABLE_NAME}

  AttributeDefinitions:
    - AttributeName: id
      AttributeType: S

    # - AttributeName: archived
    #   AttributeType: BOOL

    # - AttributeName: categories
    #   AttributeType: SS

    # - AttributeName: images
    #   AttributeType: SS

    # - AttributeName: created_at
    #   AttributeType: N

  KeySchema:
    - AttributeName: id
      KeyType: HASH

  BillingMode: PAY_PER_REQUEST
