@startuml models

class Language {
  id : string
  code : ISO 635-1
}

class Product {
  id : string
  archieved : boolean
  caterogies : Category[]
  images : ProductImage[]
  created_at : number
}
Product --> Category
Product --> ProductImage

class ProductTranslation {
  id : string
  product_id : string
  language : Language
  name : string
  description : string
  preview_description : string
  text : string
}
ProductTranslation --> Product
ProductTranslation --> Language

class ProductEdition {
  id : string
  product_id : string
  name : string
  price : number
  availiable : boolean
}
ProductEdition --> Product

class ProductImage {
  id : string
  alias : string
}

class Category {
  id : string
  alias : string
  created_at : number
}

class CategoryTranslation {
  id : string
  category_id : string
  language : Language
  name : string
  page_text : string
}
CategoryTranslation --> Category
CategoryTranslation --> Language

class Order {
  id : string
  state : OrderState
  first_name : string
  last_name : string
  middle_name : string
  country : string
  city : string
  region : string
  address : string
  zip_code : string
  email : string
  phone_number : string
  track_code : string
  language : Language
  amount : number
  products : OrderItem[]
}
Order --> Language
Order --> OrderItem

class OrderItem {
  id : string
  product_id : string
  name : string
  price : number
  amount : number
  total_count : number
  edition : ProductEdition
}
OrderItem --> Product
OrderItem --> ProductEdition

@enduml
